if jit and jit.os == "Windows" then
    -- Make sure the Windows console is set to use the Unicode codepage
    -- (so that we can print emojis)
    os.execute("chcp 65001")
end

-- "Control Sequence Inducer"
local CSI = string.char(27) .. "["

local term = {}

local function sgr(...)
    -- "Set Graphics Rendition"
    return CSI .. table.concat({...}, ";") .. "m"
end
term.sgr = sgr

local RESET = sgr(0)
term.RESET = RESET

-- 16 color fg/bg
function string.color(s, fg, bg)
    return sgr(30 + fg, bg and (40 + bg)) .. s .. RESET
end

function string.boldcolor(s, fg, bg)
    return sgr(1, 30 + fg, bg and (40 + bg)) .. s .. RESET
end

function string.rgb(s, fg_rgb, bg_rgb)
    local c = sgr(38, 2, unpack(fg_rgb))
    if bg_rgb then c = c .. term.sgr(48, 2, unpack(bg_rgb)) end
    return c .. s .. RESET
end

term.colors = {
    black=0,
    red=1,
    green=2,
    yellow=3,
    blue=4,
    magenta=5,
    cyan=6,
    white=7
}

-- these are written manually like this (rather than generated by a 
-- higher-order function/loop) in order to be visible to 
-- the lua language server
function string.black(s) return s:color(0) end
function string.red(s) return s:color(1) end
function string.green(s) return s:color(2) end
function string.yellow(s) return s:color(3) end
function string.blue(s) return s:color(4) end
function string.magenta(s) return s:color(5) end
function string.cyan(s) return s:color(6) end
function string.white(s) return s:color(7) end

return term